apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gradle
  labels:
    app.kubernetes.io/version: "0.4"
  annotations:
    tekton.dev/pipelines.minVersion: "0.17.0"
    tekton.dev/displayName: Gradle
    tekton.dev/categories: Build Tools
    tekton.dev/tags: build-tool
    tekton.dev/platforms: "linux/amd64,linux/s390x,linux/ppc64le"
spec:
  description: >-
    This Task can be used to run a Gradle build.

  workspaces:
    - name: source
      description: The workspace consisting of the gradle project.
    - name: gradle-config
      description: The workspace consisting of the custom gradle properties provided by the user.
      optional: true

      # Ref. https://docs.gradle.org/current/userguide/gradle_directories.html
    - name: e-gradle-user-home-cache
      description: FAST BUILD - Stores global configuration properties, initialization scripts, caches, and log files. Use this for usecases like caching gradle dependencies.
      mountPath: $(params.E_GRADLE_USER_HOME)
      # Note: If E_FAST_BUILD_SUPPORT is true, then without providing this workspace, fast build will not be effective
      optional: true
    - name: e-gradle-project-build-cache
      description: FAST BUILD - Holds project build to speed up successive builds using gradle incremental task.
      mountPath: $(params.E_PROJECT_BUILD_DIR)
      # Note: If E_FAST_BUILD_SUPPORT is true, then without providing this workspace, fast build will not be effective
      optional: true
    - name: e-gradle-project-local-cache
      description: FAST BUILD - Holds project specific cache directory (.gradle) generated by Gradle. This is needed along with e-gradle-project-build-cache to support incremental task.
      mountPath: $(workspaces.source.path)/$(params.PROJECT_DIR)/.gradle
      # Note: If E_FAST_BUILD_SUPPORT is true, then without providing this workspace, fast build will not be effective
      optional: true

  params:
    - name: GRADLE_IMAGE
      description: Gradle base image.
      type: string
      default: docker.io/library/gradle:7.6-jdk8@sha256:ebda657f66e04cfa9f152896b4fa70bea4b80561a836adddca3ed85d622f8898
    - name: PROJECT_DIR
      description: The directory containing build.gradle
      type: string
      default: "."
    - name: TASKS
      description: 'The gradle tasks to run (default: build)'
      type: array
      default:
        - build
      # NOTE: Fields prefixed with E_ (for Extras) are added on top of original catalog tasks for more customization
    - name: E_GRADLE_USER_HOME
      description: Location of gradle dependency cache
      default: /home/gradle
    - name: E_PROJECT_BUILD_DIR
      description: Project build directory location if customized for 'fast build'
      # default: $(workspaces.source.path)/"$(params.PROJECT_DIR)"/build
      default: "/tmp/project/build"
    - name: E_FAST_BUILD_SUPPORT
      description: This enables gradle dependency caching (e-gradle-user-home-cache), caching build (e-gradle-project-build-cache), supporting incremental task (e-gradle-project-local-cache)
      type: string
      default: "false"

  steps:
    - name: gradle-tasks
      image: $(params.GRADLE_IMAGE)
      env:
        - name: GRADLE_USER_HOME
          value: "/home/gradle"
      workingDir: $(workspaces.source.path)/$(params.PROJECT_DIR)
      args:
        - "$(params.TASKS)"
      script: |
        #!/usr/bin/env bash
        whoami
        if [[ "$(workspaces.gradle-config.bound)" == "true" ]]; then
          echo "gradle-config workspace is bound"
          if [[ -f $(workspaces.gradle-config.path)/gradle.properties ]]; then
            echo "copying gradle.properties to /home/gradle"
            cp "$(workspaces.gradle-config.path)/gradle.properties" /home/gradle
          fi
        fi

        if [[ -f gradlew ]]; then
          cmd="./gradlew $*"
        else
          cmd="gradle $*"
        fi

        echo "debug start"
        echo PROJECT_DIR="$(params.PROJECT_DIR)"
        echo Default project build dir = "$(workspaces.source.path)/$(params.PROJECT_DIR)/build"
        echo E_PROJECT_BUILD_DIR="$(params.E_PROJECT_BUILD_DIR)"
        echo "debug end"

        # E_: Customized to configure separate build directory location to be able mount on a separate pvc, so that the pvc holding codebase can be cleaned by git-clone task with no issue.
        # [[ -n "$(params.E_PROJECT_BUILD_DIR)" ]] && cmd="$cmd -PbuildDir=$(params.E_PROJECT_BUILD_DIR)"
        # [[ "$(params.E_FAST_BUILD_SUPPORT)" == "true" ]] && mkdir -p "$(params.E_PROJECT_BUILD_DIR)" && cmd="$cmd -PbuildDir=$(params.E_PROJECT_BUILD_DIR)"
        [[ "$(params.E_FAST_BUILD_SUPPORT)" == "true" ]] && cmd="$cmd -PbuildDir=$(params.E_PROJECT_BUILD_DIR)"
        [[ "$(params.E_FAST_BUILD_SUPPORT)" == "true" ]] && workspaces.e-gradle-user-home-cache.bound="false"
        echo home-cache="$(workspaces.e-gradle-user-home-cache.bound)"

        echo "Running gradle task with command below"
        echo "$cmd"
        eval "$cmd"