apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: pipelinerun-context
spec:
  params:
    # - name: pipelinecontext
    #   type: object
    #   Properties:
    #     Property:
    #       -

    #       -
    # - name: pipelinecontext
    # - name: pipeline-uid
    #   default: "$(context.pipelineRun.uid)"
    # - name: pipeline-name
    #   default: "$(context.pipeline.name)"
    # - name: pipelineRun-name
    #   default: "$(context.pipelineRun.name)"
    # - name: pipelineRun-namespace
    #   default: "$(context.pipelineRun.namespace)"
    # - name: pipelineTask-retries
    #   default: "$(context.pipelineTask.retries)"

  steps:
    - name: show-context
      image: mirror.gcr.io/ubuntu
      script: |
        echo "Task name: $(context.task.name)"
        echo "TaskRun name: $(context.taskRun.name)"
        # echo "Pipeline uid: $(context.pipelineRun.uid)"
        # echo "Pipeline name: $(context.pipeline.name)"
        # echo "PipelineRun name: $(context.pipelineRun.name)"
        # echo "PipelineRun namespace: $(context.pipelineRun.namespace)"