apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kaniko-warmer
spec:
  params:
    - name: CACHE_DIR
      default: /cache
      description: Location of the local cache
    - name: DOCKERFILE
      description: dockerfile location relative to the SOURCE workspace

  workspaces:
    - name: source
      description: source of the code repo containing the dockerfile
    - name: e_kaniko_warmer_cache
      description: kaniko cache source
      mountPath: "$(params.CACHE_DIR)"

  steps:
    - name: kaniko-warmer
      image: gcr.io/kaniko-project/warmer:latest
      workingDir: $(workspaces.source.path)
      args:
        - --cache-dir=$(params.CACHE_DIR)
        # - --image=docker.io/eclipse-temurin:17-jdk-alpine
        # - --image=docker.io/eclipse-temurin:17-jre-alpine
        - --dockerfile=$(params.DOCKERFILE)