apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: deploy-pipeline
spec:
  params:

    # For kaniko-warmer task
    - name: kaniko-warmer
      type: object
      description: Parameters of kaniko-warmer task
      properties:
        kaniko-cachedir:
          type: string
        dockerfile:
          type: string
      default:
        kaniko-cachedir: "$(params.kaniko.kaniko-cachedir)"
        dockerfile: "$(params.kaniko.dockerfile)"

    # For kaniko task
    - name: kaniko
      type: object
      description: Parameters of kaniko task
      properties:
        image:
          type: string
        image-tag:
          type: string
        dockerfile:
          type: string
        context:
          type: string
        builder-image:
          type: string
        kaniko-cachedir:
          type: string
        gradle-user-home:
          type: string
        docker-internal-cache-location:
          type: string
        docker-context-cache-location:
          type: string
      default:
        # image-tag: "latest"
        context: "."
        # builder-image: "gcr.io/kaniko-project/executor:v1.23.1@sha256:7914350eda14b43f3dcc6925afca88d6b7ba5dff13d221bb70ef44d4da73a1e8"
        gradle-user-home: "/root/.gradle"
        docker-internal-cache-location: "/workspace/binary"
        docker-context-cache-location: "$(params.common.build-artifacts-root)"
    - name: kaniko-params-extra-args
      type: array

    # Pipeline commons
    - name: common
      type: object
      properties:
        build-artifacts-root:
          type: string
        project-build-dir-name:
          type: string
      default:
        build-artifacts-root: "/tmp/myproject/build-artifacts"
        project-build-dir-name: "build"

      # Debugging purpose
    - name: debug
      type: object
      description: all debug switches and properties
      properties:
        # clone-source-repo-disabled:
        #   type: string
        # build-test-publish-artifacts-disabled:
        #   type: string
        kaniko-warmer-disabled:
          type: string
        kaniko-build-and-push-image-disabled:
          type: string
      default:
        # clone-source-repo-disabled: "false"
        # build-test-publish-artifacts-disabled: "false"
        kaniko-warmer-disabled: "false"
        kaniko-build-and-push-image-disabled: "false"

  workspaces:
    - name: shared-workspace
    # - name: git-ssh-credentials
    - name: docker-credentials

  results:
    # - name: repo-details
    #   type: object
    #   description: "repo details of source codebase"
    #   value: "$(finally.aggregate-results.results.repo-details)"
    - name: image-details
      type: object
      description: "details of image generated from dockerfile"
      value: "$(finally.aggregate-results.results.image-details)"

  tasks:
    - name: pipeline-ctx
      taskSpec:
          steps:
            - name: ctx
              image: mirror.gcr.io/ubuntu
              script: |
                echo "Pipeline: $(context.pipeline.name)"
                echo "PipelineRun: $(context.pipelineRun.name)"
                echo "PipelineRun uid: $(context.pipelineRun.uid)"
                echo "PipelineRun namespace: $(context.pipelineRun.namespace)"

    - name: kaniko-warmer
      when:
        - input: "$(params.debug.kaniko-warmer-disabled)"
          operator: in
          values:
            - "false"
      taskRef:
        resolver: git
        params:
          - name: repo
            value: P-tekton-catalog-org
          - name: pathInRepo
            value: task/image-build/kaniko/kaniko-warmer/kaniko-warmer.yaml

      params:
        - name: CACHE_DIR
          value: "$(params.kaniko-warmer.kaniko-cachedir)"
        - name: DOCKERFILE
          value: "$(params.kaniko-warmer.dockerfile)"

      workspaces:
        - name: source
          workspace: shared-workspace
          subPath: source-code/
        - name: e_kaniko_warmer_cache
          workspace: shared-workspace
          subPath: kaniko/kaniko-cache/

      runAfter:
        - "pipeline-ctx"

    - name: kaniko-build-and-push-image
      when:
        - input: "$(params.debug.kaniko-build-and-push-image-disabled)"
          operator: in
          values:
            - "false"
      taskRef:
        resolver: git
        params:
          - name: repo
            value: P-tekton-catalog-org
          - name: pathInRepo
            value: task/image-build/kaniko/kaniko.yaml

      params:
        - name: IMAGE
          # value: "$(params.kaniko.image):$(tasks.clone-source-repo.results.commit)"
          value: "$(params.kaniko.image):$(params.kaniko.image-tag)"
        - name: BUILDER_IMAGE
          value: "$(params.kaniko.builder-image)"
        - name: DOCKERFILE
          value: "$(params.kaniko.dockerfile)"
        - name: CONTEXT
          value: "$(params.kaniko.context)"
        - name: EXTRA_ARGS
          value: ["$(params.kaniko-params-extra-args)"]
        - name: E_KANIKO_CACHE_DIR
          value: "$(params.kaniko.kaniko-cachedir)"
        - name: E_DOCKER_INTERNAL_CACHE_LOCATION
          value: "$(params.kaniko.docker-internal-cache-location)"
        - name: E_DOCKER_CONTEXT_CACHE_LOCATION
          value: "$(params.kaniko.docker-context-cache-location)"

      workspaces:
        - name: source
          workspace: shared-workspace
          subPath: source-code/
        - name: e_kaniko_cache
          workspace: shared-workspace
          subPath: kaniko/kaniko-cache/
        - name: e_docker_internal_cache
          workspace: shared-workspace
          subPath: kaniko/docker-internal-cache/
        - name: e_gradle_cache
          workspace: shared-workspace
          subPath: kaniko/gradle-cache/
        - name: e_project_build_artifact_root_cache
          workspace: shared-workspace
          subPath: gradle-cache/project/artifacts-cache/

        - name: dockerconfig
          workspace: docker-credentials

      runAfter:
        - "kaniko-warmer"

  finally:
    - name: all-tasks-status
      displayName: "Status"
      params:
        - name: aggregateTasksStatus
          value: "$(tasks.status)"
      taskSpec:
        params:
          - name: aggregateTasksStatus
        steps:
          - name: status
            image: mirror.gcr.io/ubuntu
            script: |
              echo "Tasks status: $(params.aggregateTasksStatus)"
    - name: report-pipeline-failure
      when:
        - input: "$(tasks.status)"
          operator: in
          values:
            - "Failed"
            - "None"
      params:
        # - name: clone-source-repo-status
        #   value: "$(tasks.clone-source-repo.status)"
        # - name: build-test-publish-artifacts-status
        #   value: "$(tasks.build-test-publish-artifacts.status)"
        - name: kaniko-warmer-status
          value: "$(tasks.kaniko-warmer.status)"
        - name: kaniko-build-and-push-image-status
          value: "$(tasks.kaniko-build-and-push-image.status)"
      taskSpec:
        params:
          # - name: clone-source-repo-status
          # - name: build-test-publish-artifacts-status
          - name: kaniko-warmer-status
          - name: kaniko-build-and-push-image-status
        steps:
          - name: failed
            image: mirror.gcr.io/ubuntu
            script: |
              echo "One or more tasks failed"
              echo "task: kaniko-warmer \t\t\tstatus: $(params.kaniko-warmer-status)"
              echo "task: kaniko-build-and-push-image \t\tstatus: $(params.kaniko-build-and-push-image-status)"
              echo
              echo "[ToDo] Notify on slack channel (use tekton task for slack)"
    - name: report-pipeline-success
      when:
        - input: "$(tasks.status)"
          operator: in
          values:
            - "Succeeded"
            - "Completed"
      params:
        # - name: clone-source-repo-status
        #   value: "$(tasks.clone-source-repo.status)"
        # - name: build-test-publish-artifacts-status
        #   value: "$(tasks.build-test-publish-artifacts.status)"
        - name: kaniko-warmer-status
          value: "$(tasks.kaniko-warmer.status)"
        - name: kaniko-build-and-push-image-status
          value: "$(tasks.kaniko-build-and-push-image.status)"
      taskSpec:
        params:
          # - name: clone-source-repo-status
          # - name: build-test-publish-artifacts-status
          - name: kaniko-warmer-status
          - name: kaniko-build-and-push-image-status
        steps:
          - name: success
            image: mirror.gcr.io/ubuntu
            script: |
              echo "All tasks passed"
              echo "task: kaniko-warmer \t\t\tstatus: $(params.kaniko-warmer-status)"
              echo "task: kaniko-build-and-push-image \t\tstatus: $(params.kaniko-build-and-push-image-status)"
              echo
              echo "[ToDo] Notify on slack channel (use tekton task for slack)"

    - name: aggregate-results
      when:
        - input: "$(tasks.status)"
          operator: in
          values:
            - "Succeeded"
            # "Completed" is NOT allowed, since some tasks may be skipped due to when condition and corresponding results would not be available, and this task would never start
      taskSpec:
        results:
          # - name: repo-details
          #   type: object
          #   properties:
          #     url:
          #       type: string
          #     commit:
          #       type: string
          #     committer-date:
          #       type: string
          - name: image-details
            type: object
            properties:
              url:
                type: string
              digest:
                type: string
            # default:
            #   url: "error"
            #   digest: "error"
        steps:
          - name: write-result
            image: bash:latest
            script: |
              #!/usr/bin/env bash
              echo -n "{\"url\":\"$(tasks.kaniko-build-and-push-image.results.IMAGE_URL)\",\"digest\":\"$(tasks.kaniko-build-and-push-image.results.IMAGE_DIGEST)\"}" | tee $(results.image-details.path)