apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: p1
spec:
  params:
    # For git-clone task
    - name: git-clone
      type: object
      description: Git repo specific details
      properties:
        url:
          type: string
        revision:
          type: string
        refspec:
          type: string
        submodules:
          type: string
        depth:
          type: string
        sslVerify:
          type: string
        crtFileName:
          type: string
        subdirectory:
          type: string
        sparseCheckoutDirectories:
          type: string
        deleteExisting:
          type: string
        httpProxy:
          type: string
        httpsProxy:
          type: string
        noProxy:
          type: string
        verbose:
          type: string
        gitInitImage:
          type: string
        userHome:
          type: string
      default:
        url: "git@github.com:IndranilNandy/demo-app-to-test-pipeline"
        revision: "master"
        refspec: ""
        submodules: "true"
        depth: "1"
        sslVerify: "true"
        crtFileName: "ca-bundle.crt"
        subdirectory: ""
        sparseCheckoutDirectories: ""
        deleteExisting: "true"
        httpProxy: ""
        httpsProxy: ""
        noProxy: ""
        verbose: "true"
        gitInitImage: "gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.44.5"
        userHome: "/home/git"

    # For gradle task
    - name: gradle
      type: object
      description: Parameters of gradle task
      properties:
        gradle-image:
          type: string
        project-dir:
          type: string
        # Currently 'array' key-type not supported
        # tasks:
        #   type: array
        gradle-user-home:
          type: string
        project-build-dir:
          type: string
      default:
        gradle-image: "gradle:8.7.0-jdk17"
        project-dir:  "."
        # tasks:
        #   - "build"
        gradle-user-home: "/home/gradle"
        project-build-dir: "$(params.common.build-artifacts-root)/$(params.common.project-build-dir-name)"
    - name: gradle-params-tasks
      type: array
      default:
        - build

    # For kaniko-warmer task
    - name: kaniko-warmer
      type: object
      description: Parameters of kaniko-warmer task
      properties:
        kaniko-cachedir:
          type: string
        dockerfile:
          type: string
      default:
        kaniko-cachedir: "$(params.kaniko.kaniko-cachedir)"
        dockerfile: "$(params.kaniko.dockerfile)"

    # For kaniko task
    - name: kaniko
      type: object
      description: Parameters of kaniko task
      properties:
        image:
          type: string
        dockerfile:
          type: string
        context:
          type: string
        builder-image:
          type: string
        kaniko-cachedir:
          type: string
        gradle-user-home:
          type: string
        docker-internal-cache-location:
          type: string
        docker-context-cache-location:
          type: string
      default:
        # image: "$(params.app-image):$(tasks.clone-source-repo.results.commit)"
        context: "."
        gradle-user-home: "/root/.gradle"
        docker-internal-cache-location: "/workspace/binary"
        docker-context-cache-location: "$(params.common.build-artifacts-root)"
    # - name: app-image
    # - name: builder-image
    # - name: dockerfile
    # - name: context
    - name: kaniko-params-extra-args
      type: array
    # - name: kaniko-cachedir
    # - name: binary-cache

    # Pipeline specific
    - name: common
      type: object
      properties:
        build-artifacts-root:
          type: string
        project-build-dir-name:
          type: string
      default:
        build-artifacts-root: "/tmp/myproject/build-artifacts"
        project-build-dir-name: "build"
    # - name: build-artifacts-root
    #   default: /tmp/myproject/build-artifacts
    # - name: project-build-dir-name
    #   default: build

      # Debugging purpose
    - name: debug
      type: object
      description: all debug switches and properties
      properties:
        clone-source-repo-disabled:
          type: string
        build-test-publish-artifacts-disabled:
          type: string
        kaniko-warmer-disabled:
          type: string
        kaniko-build-and-push-image-disabled:
          type: string
      default:
        clone-source-repo-disabled: "false"
        build-test-publish-artifacts-disabled: "false"
        kaniko-warmer-disabled: "false"
        kaniko-build-and-push-image-disabled: "false"

    # - name: clone-source-repo-debug-disabled
    #   default: "false"
    # - name: build-test-publish-artifacts-debug-disabled
    #   default: "false"
    # - name: kaniko-warmer-debug-disabled
    #   default: "false"
    # - name: kaniko-build-and-push-image
    #   default: "false"

  workspaces:
    - name: shared-workspace
    # - name: git-ssh-credentials
    - name: docker-credentials

  results:
    - name: repo-details
      type: object
      description: "repo details of source codebase"
      value: "$(finally.aggregate-results.results.repo-details)"
    - name: image-details
      type: object
      description: "details of image generated from dockerfile"
      value: "$(finally.aggregate-results.results.image-details)"

  tasks:
    - name: pipeline-ctx
      taskSpec:
          steps:
            - name: ctx
              image: mirror.gcr.io/ubuntu
              script: |
                echo "Pipeline: $(context.pipeline.name)"
                echo "PipelineRun: $(context.pipelineRun.name)"
                echo "PipelineRun uid: $(context.pipelineRun.uid)"
                echo "PipelineRun namespace: $(context.pipelineRun.namespace)"

    - name: clone-source-repo
      when:
        - input: "$(params.debug.clone-source-repo-disabled)"
          operator: in
          values:
            - "false"
      taskRef:
        resolver: git
        params:
          - name: repo
            value: P-tekton-catalog-org
          - name: pathInRepo
            value: task/scm/git-clone/git-clone.yaml

      params:
        - name: url
          value: "$(params.git-clone.url)"
        - name: revision
          value: "$(params.git-clone.revision)"
        - name: depth
          value: "$(params.git-clone.depth)"
      workspaces:
        - name: output
          workspace: shared-workspace
          subPath: source-code/

      runAfter:
        - "pipeline-ctx"

    - name: build-test-publish-artifacts
      when:
        - input: "$(params.debug.build-test-publish-artifacts-disabled)"
          operator: in
          values:
            - "false"
      taskRef:
        resolver: git
        params:
          - name: repo
            value: P-tekton-catalog-org
          - name: pathInRepo
            value: task/build-tool/gradle/gradle.yaml

      params:
        - name: GRADLE_IMAGE
          value: "$(params.gradle.gradle-image)"
        - name: PROJECT_DIR
          value: "$(params.gradle.project-dir)"
        - name: TASKS
          value: ["$(params.gradle-params-tasks)"]
        - name: E_PROJECT_BUILD_DIR_CUSTOM
          value: "$(params.gradle.project-build-dir)"
          # value: "$(params.common.build-artifacts-root)/$(params.common.project-build-dir-name)"
        - name: E_GRADLE_USER_HOME
          value: "$(params.gradle.gradle-user-home)"

      workspaces:
        - name: source
          workspace: shared-workspace
          subPath: source-code/
        - name: e-gradle-user-home-cache
          workspace: shared-workspace
          subPath: gradle-cache/user-home/
        - name: e-gradle-project-build-cache
          workspace: shared-workspace
          subPath: gradle-cache/project/artifacts-cache/$(params.common.project-build-dir-name)
        - name: e-gradle-project-local-cache
          workspace: shared-workspace
          subPath: gradle-cache/project/local-cache/

      runAfter:
        - "clone-source-repo"

    - name: kaniko-warmer
      when:
        - input: "$(params.debug.kaniko-warmer-disabled)"
          operator: in
          values:
            - "false"
      taskRef:
        resolver: git
        params:
          - name: repo
            value: P-tekton-catalog-org
          - name: pathInRepo
            value: task/image-build/kaniko/kaniko-warmer/kaniko-warmer.yaml

      params:
        - name: CACHE_DIR
          value: "$(params.kaniko-warmer.kaniko-cachedir)"
        - name: DOCKERFILE
          value: "$(params.kaniko-warmer.dockerfile)"

      workspaces:
        - name: source
          workspace: shared-workspace
          subPath: source-code/
        - name: e_kaniko_warmer_cache
          workspace: shared-workspace
          subPath: kaniko/kaniko-cache/

      runAfter:
        - "build-test-publish-artifacts"

    - name: kaniko-build-and-push-image
      when:
        - input: "$(params.debug.kaniko-build-and-push-image-disabled)"
          operator: in
          values:
            - "false"
      taskRef:
        resolver: git
        params:
          - name: repo
            value: P-tekton-catalog-org
          - name: pathInRepo
            value: task/image-build/kaniko/kaniko.yaml

      params:
        - name: IMAGE
          value: "$(params.kaniko.image):$(tasks.clone-source-repo.results.commit)"
        - name: BUILDER_IMAGE
          value: "$(params.kaniko.builder-image)"
        - name: DOCKERFILE
          value: "$(params.kaniko.dockerfile)"
        - name: CONTEXT
          value: "$(params.kaniko.context)"
        - name: EXTRA_ARGS
          value: ["$(params.kaniko-params-extra-args)"]
        - name: E_KANIKO_CACHE_DIR
          value: "$(params.kaniko.kaniko-cachedir)"
        - name: E_DOCKER_INTERNAL_CACHE_LOCATION
          value: "$(params.kaniko.docker-internal-cache-location)"
        - name: E_DOCKER_CONTEXT_CACHE_LOCATION
          value: "$(params.kaniko.docker-context-cache-location)"

      workspaces:
        - name: source
          workspace: shared-workspace
          subPath: source-code/
        - name: e_kaniko_cache
          workspace: shared-workspace
          subPath: kaniko/kaniko-cache/
        - name: e_docker_internal_cache
          workspace: shared-workspace
          subPath: kaniko/docker-internal-cache/
        - name: e_gradle_cache
          workspace: shared-workspace
          subPath: kaniko/gradle-cache/
        - name: e_project_build_artifact_root_cache
          workspace: shared-workspace
          subPath: gradle-cache/project/artifacts-cache/

        - name: dockerconfig
          workspace: docker-credentials

      runAfter:
        - "kaniko-warmer"

    # - name: show-all-results
    #   taskSpec:
    #     results:
    #       - name: repo-details
    #         type: object
    #         properties:
    #           url:
    #             type: string
    #           commit:
    #             type: string
    #           committer-date:
    #             type: string
    #     steps:
    #       - name: write-result
    #         image: bash:latest
    #         script: |
    #           #!/usr/bin/env bash
    #           echo -n "{\"url\":\"$(tasks.clone-source-repo.results.url)\",\"commit\":\"$(tasks.clone-source-repo.results.commit)\",\"committer-date\":\"$(tasks.clone-source-repo.results.committer-date)\"}" | tee $(results.repo-details.path)
    #           echo first value = "$(results.repo-details.path)"
    #           cat "$(results.repo-details.path)"

    #   runAfter:
    #     - "kaniko-build-and-push-image"
  finally:
    - name: all-tasks-status
      params:
        - name: aggregateTasksStatus
          value: "$(tasks.status)"
      taskSpec:
        params:
          - name: aggregateTasksStatus
        steps:
          - name: status
            image: mirror.gcr.io/ubuntu
            script: |
              echo "Tasks status: $(params.aggregateTasksStatus)"
    - name: aggregate-results
      taskSpec:
        results:
          - name: repo-details
            type: object
            properties:
              url:
                type: string
              commit:
                type: string
              committer-date:
                type: string
          - name: image-details
            type: object
            properties:
              url:
                type: string
              digest:
                type: string
        steps:
          - name: write-result
            image: bash:latest
            script: |
              #!/usr/bin/env bash
              echo -n "{\"url\":\"$(tasks.clone-source-repo.results.url)\",\"commit\":\"$(tasks.clone-source-repo.results.commit)\",\"committer-date\":\"$(tasks.clone-source-repo.results.committer-date)\"}" | tee $(results.repo-details.path)
              echo -n "{\"url\":\"$(tasks.kaniko-build-and-push-image.results.IMAGE_URL)\",\"digest\":\"$(tasks.kaniko-build-and-push-image.results.IMAGE_DIGEST)\"}" | tee $(results.image-details.path)
              echo -e revision="$(params.git-clone.revision)"
              echo -e build-dir="$(params.gradle.project-build-dir)"

