apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: sample-pipeline
spec:
  tasks:
    - name: sample-task
      taskSpec:
        steps:
          - name: check
            image: mirror.gcr.io/ubuntu
            script: |
              echo testing done