
apiVersion: tekton.dev/v1beta1
kind: StepAction
metadata:
  name: task-context
spec:
  image: mirror.gcr.io/ubuntu
  script: |
    echo "Task info:"
    echo "\t\tName:\t$(context.task.name)"
    echo "\t\tTaskRun:\t$(context.taskRun.name)"
    echo "\t\tTaskRun uid:\t$(context.taskRun.uid)"
    echo "\t\tTaskRun namespace:\t$(context.taskRun.namespace)"