---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: sample-catalog-task-gradle-fresh-build
spec:
  workspaces:
    - name: shared-workspace-gradle
    - name: gradle-config

  tasks:
    - name: fetch-wrapper-code
      taskRef:
        resolver: git
        params:
          - name: repo
            value: P-tekton-catalog-org
          - name: pathInRepo
            value: task/scm/git-clone/git-clone.yaml
      workspaces:
        - name: output
          workspace: shared-workspace-gradle
          subPath: repo2/source-code/
      params:
        - name: url
          value: https://github.com/BastiaanN/simple-gradle-wrapper
        - name: subdirectory
          value: "wrapper-test"
        - name: deleteExisting
          value: "true"

    - name: gradle-wrapper-run
      taskRef:
        resolver: git
        params:
          - name: repo
            value: P-tekton-catalog-org
          - name: pathInRepo
            value: task/build-tool/gradle/gradle.yaml
      runAfter:
        - fetch-wrapper-code
      params:
        - name: TASKS
          value:
            - build
            - --console=verbose
        - name: PROJECT_DIR
          value: "wrapper-test"
        - name: GRADLE_IMAGE
          value: docker.io/library/eclipse-temurin:17-ubi9-minimal@sha256:19c66566a0a802df5674301b223683ffbcf56cf18488a37a21d53e3d09df57d1
        # - name: E_PROJECT_BUILD_DIR
        #   value: /tmp/myproject/build
        # - name: E_FAST_BUILD_SUPPORT
        #   value: "true"
      workspaces:
        - name: source
          workspace: shared-workspace-gradle
          subPath: repo2/source-code/
        - name: gradle-config
          workspace: gradle-config
        - name: e-gradle-user-home-cache
          workspace: shared-workspace-gradle
          subPath: repo2/gradle-cache/user-home/
        - name: e-gradle-project-build-cache
          workspace: shared-workspace-gradle
          subPath: repo2/gradle-cache/project/build-cache/
        - name: e-gradle-project-local-cache
          workspace: shared-workspace-gradle
          subPath: repo2/gradle-cache/project/local-cache/