# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: dummy-not-used-pvc
# spec:
#   storageClassName: k8-default-sc-with-clustered-nfs-server
#   resources:
#     requests:
#       storage: 1Mi
#   accessModes:
#     - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-catalog-pipeline-p1-ctx-not-mounted-pvc
spec:
  storageClassName: k8-default-sc-with-clustered-nfs-server
  resources:
    requests:
      storage: 1024Mi
  accessModes:
    - ReadWriteOnce